import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased dark`}>
        <nav className="border-b">
          <div className="container mx-auto flex h-14 items-center px-4">
            <Link href="/" className="font-semibold mr-8">
              Jobes
            </Link>
            <div className="flex gap-6">
              <Link href="/companies" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                Companies
              </Link>
              <Link href="/applications" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                Applications
              </Link>
              <Link href="/tools" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                Tools
              </Link>
            </div>
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
